[theme]
base = "light"
primaryColor = "#2f6d54"
backgroundColor = "#f5f7f8"
secondaryBackgroundColor = "#e4e9ed"
textColor = "#173527"
font = "sans serif"

[theme.light]
primaryColor = "#2f6d54"
backgroundColor = "#f5f7f8"
secondaryBackgroundColor = "#e4e9ed"
textColor = "#173527"

[theme.dark]
primaryColor = "#ff7d65"
backgroundColor = "#0f1512"
secondaryBackgroundColor = "#18211b"
textColor = "#f2efe7"
